stages:
  data_ingestion:
    cmd: python src/mlploject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlploject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python src/mlploject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlploject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion
      - schema.yaml
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python src/mlploject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlploject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - schema.yaml
      - artifacts/data_ingestion
    outs:
      - artifacts/data_transformation
    
  model_trainer:
    cmd: python src/mlploject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlploject/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - schema.yaml
      - artifacts/data_transformation
    params:
      - Elasticnet
    outs:
      - artifacts/model_trainer
  
  model_evaluation:
    cmd: python src/mlploject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlploject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - schema.yaml
      - artifacts/data_transformation
    params:
      - Elasticnet
    outs:
      - artifacts/model_evaluation/metrics.json

